language: node_js
node_js:
  - '4.1'

cache:
  directories:
    - node_modules
    - jspm_modules
    - ~/.jspm

install:
  - npm install
  - npm install -g gulp
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GH_TOKEN
  - jspm install -y
  
script: 
  - gulp bundle-cdn
  
before_deploy:
  - rm -rf node_modules
  - rm -rf jspm_modules
  
deploy:  
  skip_cleanup: true
  provider: azure_web_apps
  verbose: false
  #quiet: true
