language: node_js
node_js:
  - '5.0'

cache:
  directories:
    - node_modules
    - jspm_modules
    - ~/.jspm

install:
  - npm install -g gulp
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GH_TOKEN
  - jspm install -y
  
script: 
  - gulp build
  - gulp bundle
  
deploy:  
  skip_cleanup: true
  provider: azure_web_apps
  verbose: true
