language: node_js
node_js:
  - '5.0'

cache:
  directories:
    - node_modules
    - jspm_modules
    - ~/.jspm

before_install:
  - npm install -g gulp
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GH_TOKEN
  - jspm install -y
  
install: 
  - gulp build
  - gulp bundle

before_deploy:
  - cd dist
  - git add -f *
  - cd ../jspm_packages
  - git add -f system.js
  - git commit -am "Travis CI"
  
  
deploy:  
  skip_cleanup: true
  provider: azure_web_apps
  verbose: true
  local-dir: dist
