language: node_js
node_js:
  - '4.1'

env:
  global:
    - TMPDIR=/tmp

cache:
  directories:
    - node_modules
    - jspm_modules
    - ~/.jspm

install:
  - npm install
  - npm install -g gulp
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GH_TOKEN
  - jspm install -y
  
script: 
  - gulp bundle-cdn
  
before_deploy:
  - mkdir /tmp/enttoi
  - mv node_modules jspm_modules build environments src .vscode -t /tmp/enttoi
  - ls /tmp/enttoi
  - cp /tmp/enttoi/jspm_packages/system.js jspm_packages/
  
deploy:  
  skip_cleanup: true
  provider: azure_web_apps
  verbose: false
  quiet: true
  
